services:
  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/walpanel
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/walpanel:/walpanel/app
    env_file:
      - .env
    command: >
      bash -c "cd /walpanel/app &&  alembic upgrade head &&  (uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload)"
