services:
  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/walpanel
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/walpanel:/walpanel/app
    env_file:
      - .env
