services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/walpanel
      # - ./backup:/walpanel/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/walpanel:/walpanel/app
    env_file:
      - .env
